# Generated by Django 5.1.2 on 2024-12-02 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('daraja', models.CharField(max_length=50)),
                ('ustoz', models.CharField(max_length=100)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chegirma', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('baho', models.PositiveIntegerField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izohlar', to='main.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izohlar', to='main.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanlanganlar', to='main.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanlanganlar', to='main.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('holat', models.CharField(max_length=50)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xaridlar', to='main.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xaridlar', to='main.profil')),
            ],
        ),
    ]
